"""PlatformIO pre-build step: gzip web/*.html into src/web_assets.h so the
pages ship inside the firmware image (one file to flash)."""
import gzip
import pathlib

Import("env")  # noqa: F821 - injected by PlatformIO

ROOT = pathlib.Path(env.subst("$PROJECT_DIR"))  # noqa: F821
PAGES = {"INDEX_HTML_GZ": "index.html", "SETUP_HTML_GZ": "setup.html"}


def c_array(name, data):
    body = ",".join(str(b) for b in data)
    return f"const uint8_t {name}[] = {{{body}}};\nconst size_t {name}_LEN = {len(data)};\n"


lines = ["// Generated by tools/embed_web.py - do not edit.", "#pragma once",
         "#include <cstddef>", "#include <cstdint>", ""]
for name, file in PAGES.items():
    raw = (ROOT / "web" / file).read_bytes()
    lines.append(c_array(name, gzip.compress(raw, compresslevel=9, mtime=0)))
text = "\n".join(lines)
target = ROOT / "src" / "web_assets.h"
if not target.exists() or target.read_text() != text:
    target.write_text(text)
